# Generated by Django 3.1.3 on 2021-05-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0004_auto_20210501_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.country'),
        ),
    ]
