# Generated by Django 3.1.3 on 2021-05-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210308_2208'),
        ('ums', '0003_auto_20210308_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.airline'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.destination'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.hotel'),
        ),
    ]
