# Generated by Django 3.1.3 on 2021-03-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineName', models.CharField(max_length=200, null=True)),
                ('fare', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=200, null=True)),
                ('fare', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrekDestination',
        ),
    ]
