# Generated by Django 3.1.3 on 2021-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrekDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Langtang', 'Langtang'), ('Annapurna Circuit', 'Annapurna Circuit'), ('Everest Base Camp', 'Everest Base Camp'), ('Ghorepani Poon Hill', 'Ghorepani Poon Hill'), ('Upper Mustang', 'Upper Mustang')], max_length=200, null=True)),
            ],
        ),
    ]
